doris:
  host: 172.16.33.11
  port: 9030
  database: hyy
  username: root
  password: Hieyoung123

deepseek:
  base_url: https://ark.cn-beijing.volces.com/api/v3
  api_key: 4c774fce-4316-4fd7-a16e-5703cbd92a7e
  model: deepseek-v3-250324
  timeout: 30
